spring:
  application:
    name: "tcc-signer-api-local"
  output:
    ansi:
      enabled: always
scheduler:
  prepare-to-sign:
    cron: "0 */1 * * * *"
  check-signatures:
    cron: "30 */1 * * * * "
vaadin:
  devmode-caching: true
  launch-browser: true
  launch-browser-delay: 30