spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGODB_URI}
  application:
    name: "tcc-signer-api"
  cloud:
    openfeign:
      client:
        config:
          documenso-client:
            url: "${DOCUMENSO_API_URL}"
            default-request-headers:
              Authorization: "Bearer ${DOCUMENSO_API_TOKEN}"
            logger-level: basic
            connect-timeout: 5000
            read-timeout: 5000
  jackson:
    deserialization:
      fail-on-unknown-properties: false
scheduler:
  prepare-to-sign:
    cron: "* 10 */3 * * *"
  check-signatures:
    cron: "* 30 */3 * * *"
logging:
  level:
    root: info
vaadin:
  allowed-packages: br/edu/ies/api/view
  url-mapping: /*